# Generated by Django 4.2.5 on 2023-09-23 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_description_alter_task_priority_and_more'),
    ]

    operations = [
    ]
