# Generated by Django 4.2.5 on 2023-09-24 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_rename_d_time_task_u_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='d_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
