# Generated by Django 4.2.5 on 2023-09-24 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_task_d_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='mark',
            field=models.BooleanField(default=False),
        ),
    ]
